from dataclasses import dataclass
import dataclasses

@dataclass
class Mission:
    max: int
    description: str


mission_db = {
                "naruto": (Mission(max=30, description="Spend turns under the effect of Shadow Clones."), 
                           Mission(max=20, description="Stun enemies with Uzumaki Barrage."),
                           Mission(max=25, description="Deal killing blows while in Sage Mode."),
                           Mission(max=5, description="Strike all 3 enemies with Toad Taijutsu in a single match."),
                           Mission(max=10, description="Kill enemies with only damage from Rasengan.")
                        ),
                "itachi": (Mission(max=10, description="Apply Amaterasu to all 3 enemies in a single match."),
                           Mission(max=30, description="Have enemies spend turns stunned by Tsukuyomi."),
                           Mission(max=25, description="Deal killing blows while under the effect of Susano'o."),
                           Mission(max=5, description="Win matches after Itachi has left Susano'o."),
                           Mission(max=1000, description="Absorb damage with Susano'o or Yata Mirror's destructible defense.")
                        ),
                "minato": (Mission(max=10, description="Use Partial Shiki Fuujin while Minato is below 20 health."),
                           Mission(max=20, description="Deal killing blows with Flying Raijin."),
                           Mission(max=30, description="Mark enemies with Marked Kunai."),
                           Mission(max=1, description="Use Flying Raijin 3 turns in a row, striking a marked target each time."),
                           Mission(max=25, description="Spend turns invulnerable from the effect of Flying Raijin.")
                        ),
                "neji":   (Mission(max=20, description="Deal killing blows against invulnerable enemies with Eight Trigrams - Mountain Crusher."),
                           Mission(max=25, description="Drain energy with Chakra Point Strike."),
                           Mission(max=1000, description="Deal damage with Eight Trigrams - 128 Palms."),
                           Mission(max=15, description="Protect allies with Selfless Genius."),
                           Mission(max=1, description = "Deal the winning blow with an ally buffed by Selfless Genius.")
                        ),         
                "hinata": (Mission(max=40, description="Drain energy from enemies."),
                           Mission(max=20, description = "Deal killing blows with the second half of Twin Lion Fists."),
                           Mission(max=5, description="Deal 5 killing blows with Twin Lion Fists after the first hit is countered."),
                           Mission(max=75, description="Receive hostile abilities with allies affected by Eight Trigrams - 64 Palms."),
                           Mission(max=1000, description = "Deal damage with Eight Trigrams - 64 Palms.")
                        ),
                "shikamaru": (Mission(max=600, description="Deal affliction damage with Shadow Neck Bind."),
                              Mission(max=5, description="Kill 2 enemies in the same turn with Shadow Neck Bind."),
                              Mission(max=30, description="Deal killing blows with allies against enemies affected by Shadow Bind Jutsu."),
                              Mission(max=30, description = "Pacify enemies with Shadow Pin."),
                              Mission(max=35, description="Amplify abilities with Shadow Pin.")
                            ),
                "kakashi": (Mission(max=5, description="Deal killing blows with abilities reflected by Copy Ninja Kakashi."),
                            Mission(max=15, description="Deal killing blows with Raikiri against enemies affected by Summon Nin-Dogs."),
                            Mission(max=25, description="Isolate enemies with Kamui."),
                            Mission(max=5, description="Deal killing blows with Raikiri against enemies only damaged by Kakashi."),
                            Mission(max=30, description="Spend turns under the effect of Kamui.")
                            ),
                "ichigo": (Mission(max=20, description="Strike invulnerable enemies with Getsuga Tenshou."),
                           Mission(max=20, description="Deal killing blows while Tensa Zangetsu is active."),
                           Mission(max=50, description="Gain stacks of Zangetsu Strike."),
                           Mission(max=5, description="Gain 10 stacks of Zangetsu Strike in one match."),
                           Mission(max=10, description="Get killing blows while below 30 health.")
                           ),
                "orihime": (Mission(max=60, description="Call the Shun Shun Rikka."),
                            Mission(max=25, description= "Activate the Shun Shun Rikka."),
                            Mission(max=1500, description="Restore health to allies."),
                            Mission(max=1000, description="Absorb hostile damage with Orihime's damage shields."),
                            Mission(max=10, description = "Activate Dance of the Heavenly Six.")
                            ),
                "rukia": (Mission(max=20, description="Stun enemies with First Dance - Tsukishiro."),
                          Mission(max=300, description="Deal damage with Second Dance - Hakuren."),
                          Mission(max=15, description="Use First Dance - Tsukishiro, Second Dance - Hakuren, and Third Dance - Shirafune one after another."),
                          Mission(max=5, description="Counter abilities with Third Dance - Shirafune."),
                          Mission(max=1, description = "Counter the same enemy with Third Dance - Shirafune twice in one game."),
                          ),
                "ichimaru": (Mission(max=5, description="Deal killing blows with the periodic affliction damage of Kill, Kamishini no Yari."),
                             Mission(max=25, description="Deal killing blows with the periodic afflictiond amage of Kill, Kamishini no Yari."),
                             Mission(max=100, description="Consume stacks of Kill, Kamishini no Yari."),
                             Mission(max=1, description="Keep Butou Renjin active for 8 consecutive turns."),
                             Mission(max=1, description = "Deal all 3 killing blows with Ichimaru after his teammates have died."),
                        ),
                "aizen": (Mission(max=50, description="Consume Aizen's ability marks."),
                          Mission(max=30, description="Increase the cost of enemy used abilities."),
                          Mission(max=30, description="Deal killing blows with Overwhelming Power."),
                          Mission(max=10, description="Stun the entire enemy team with Black Coffin."),
                          Mission(max=15, description="Win games without using the same ability twice in a row.")
                          ),
                "midoriya": (Mission(max=1000, description="Deal damage with SMASH!"),
                             Mission(max=500, description="Deal damage with One For All - Shoot Style."),
                             Mission(max=10, description="Counter abilities with One For All - Shoot Style."),
                             Mission(max=15, description="Deal killing blows with One For All - Shoot Style."),
                             Mission(max=10, description="Apply Air Force Gloves to all 3 enemies in a single match."),
                             ),
                "toga": (Mission(max=400, description="Deal affliction damage with Vacuum Syringe."),
                         Mission(max=40, description="Apply stacks of Vacuum Syringe or Thirsting Knife."),
                         Mission(max=1, description="Turn into all three members of the enemy team, then win the match."),
                         Mission(max=10, description="Get killing blows while transformed."),
                         Mission(max=5, description="Get killing blows while untransformed.")),
                "mirio": (Mission(max=20, description="Ignore abilities with Quirk - Permeation."),
                          Mission(max=20, description="Ignore abilities with Protect Ally."),
                          Mission(max=10, description="Strike all 3 enemies with Phantom Menace."),
                          Mission(max=15, description="Win matches with an ally at 100 health."),
                          Mission(max=20, description="Deal killing blows with Phantom Menace.")),
                "shigaraki": (Mission(max=1000, description="Deal affliction damage to enemies."),
                              Mission(max=15, description="Deal killing blows."),
                              Mission(max=1, description="Have both allies die under the effect of Destroy What You Hate, Destroy What You Love, then win the match."),
                              Mission(max=1, description="Deal all 3 killing blows of a match with a character under the effect of Destroy What You Hate, Destroy What You Love."),
                              Mission(max=10, description="Use Decaying Touch on the same enemy 3 turns in a row.")),
                "todoroki": (Mission(max=1, description="Deal the killing blow on all 3 enemies with a single Flashfreeze Heatwave."),
                            Mission(max=2000, description="Deal damage with Quirk - Half-Cold."),
                            Mission(max=25, description="Use abilities with their costs increased by Quirk - Half-Cold."),
                            Mission(max=1000, description="Deal damage to allies with Quirk - Half-Hot."),
                            Mission(max=7, description="Win matches in a row with Todoroki.")),
                "uraraka": (Mission(max=25, description="Deal killing blows with allies affected by Quirk - Zero Gravity."),
                            Mission(max=25, description="Deal killing blows with allies against enemies affected by Quirk - Zero Gravity."),
                            Mission(max=15, description="Drain energy with Comet Home Run."),
                            Mission(max=1000, description="Deal damage with allies buffed by Meteor Storm."),
                            Mission(max=20, description="Win matches with Uraraka where she deals no killing blows.")),
                "jiro": (Mission(max=20, description="Trigger retaliation effects with Counter-Balance."),
                         Mission(max=10, description="Deal killing blows with the periodic damage from Heartbeat Distortion or Heartbeat Surround."),
                         Mission(max=20, description="Deal killing blows with the amplified damage from Heartbeat Distortion or Heartbeat Surround while the other is active."),
                         Mission(max=5, description="Deal killing blows against enemies that just triggered Counter-Balance."),
                         Mission(max=5, description="Win battles wherein Jiro always has either Heartbeat Distortion or Heartbeat Surround active.")),
                "natsu": (Mission(max=500, description="Deal affliction damage with Natsu's abilities."),
                          Mission(max=15, description="Trigger Fire Dragon's Iron Fist's bonus damage effect."),
                          Mission(max=15, description="Deal killing blows with Natsu's affliction damage."),
                          Mission(max=5, description="Get the killing blow on all 3 enemies in a match."),
                          Mission(max=20, description="Damage all 3 enemies in a match.")),
                "gray": (Mission(max=40, description="Spend turns with Ice, Make Unlimited active."),
                         Mission(max=30, description="Stun enemies with Ice, Make Hammer."),
                         Mission(max=1, description="Activate Ice, Make Shield 4 times in one game, then win."),
                         Mission(max=5, description="Deal 50 damage to each enemy with Ice, Make Freeze Lancer in one game."),
                         Mission(max=40, description="Use an ability after using Ice, Make...")),
                "gajeel": (Mission(max=5, description="In a single match, deal a killing blow under the effect of Iron Shadow Dragon and Blacksteel Gajeel."),
                           Mission(max=700, description="Deal damage while under the effect of Blacksteel Gajeel."),
                           Mission(max=700, description="Deal damage while under the effect of Iron Shadow Dragon."),
                           Mission(max=20, description="Switch forms with Gajeel."),
                           Mission(max=15, description="Receive 15 harmful abilities during a single match.")),
                "wendy": (Mission(max=1000, description="Restore health to allies."),
                          Mission(max=15, description="Deal killing blows under the effect of Shredding Wedding."),
                          Mission(max=400, description="Deal damage with Shredding Wedding."),
                          Mission(max=200, description="Self-heal using Sky Dragon's Roar."),
                          Mission(max=1, description="Use a full power Troia 5 times in a single match.")),
                "erza": (Mission(max=30, description="Deal killing blows with Titania's Rampage."),
                         Mission(max=1000, description="Negate affliction damage with Heaven's Wheel Armor."),
                         Mission(max=25, description="Drain energy with Nakagami's Starlight."),
                         Mission(max=20, description="Deal killing blows with allies that are invulnerable from Adamantine Barrier."),
                         Mission(max=5, description="Win matches where Erza requips all four of her armor sets.")),
                "levy": (Mission(max=25, description="Trigger the extra damage on Solid Script - Fire."),
                         Mission(max=25, description="Deal killing blows to enemies isolated by Solid Script - Silent."),
                         Mission(max=20, description="Deal killing blows with enemies affected by Solid Script - Mask."),
                         Mission(max=1500, description="Deal damage with Solid Script - Fire."),
                         Mission(max=15, description="Use Solid Script - Mask on allies below 25 health.")),
                "laxus": (Mission(max=2000, description="Cause total damage or healing with Fairy Law."),
                          Mission(max=20, description="Deal killing blows with Lightning Dragon's Roar."),
                          Mission(max=25, description="Deal killing blows against enemies affected by Lightning Dragon's Roar's damage amplification."),
                          Mission(max=1, description="Kill the entire enemy team with a single Thunder Palance."),
                          Mission(max=5, description="Deal killing blows with the rebound damage from Thunder Palace."),
                          ),
                "saber": (Mission(max=20, description="Deal killing blows with Excalibur."),
                          Mission(max=5, description="Strike countering enemies with Excalibur."),
                          Mission(max=15, description="Deal more damage than any other character in a winning match."),
                          Mission(max=5, description="Deal more damage than any other character in a losing match."),
                          Mission(max=1000, description="Heal allies with Avalon.")),
                "jack": (Mission(max=20, description="Deal killing blows against enemies that have only been damaged by Jack."),
                         Mission(max=10, description="Deal killing blows against enemies affected by Streets of the Lost."),
                         Mission(max=1000, description="Deal affliction damage with Jack's abilities."),
                         Mission(max=20, description="Deal killing blows with Maria the Ripper."),
                         Mission(max=1, description="Spend 10 turns under the effect of Fog of London during a single match, then win the match.")),
                "chu": (Mission(max=600, description="Deal piercing damage with Relentless Assault."),
                        Mission(max=20, description="Receive damaging abilities while under the effect of Flashing Deflection."),
                        Mission(max=15, description="Deal killing blows with Gae Bolg against enemies that have destructible defense."),
                        Mission(max=350, description="Remove destructible defense with Gae Bolg."),
                        Mission(max=10, description="Deal killing blows with the third round of Relentless Assault.")),
                "astolfo": (Mission(max=25, description="Counter enemies with Casseur de Logistille."),
                            Mission(max=50, description="Gain stacks of Trap of Argalia - Down With A Touch!"),
                            Mission(max=30, description="Deal killing blows with Trap of Argalia - Down With A Touch!"),
                            Mission(max=20, description="Remove hostile effects with La Black Luna."),
                            Mission(max=10, description="Deal killing blows to enemies affected by La Black Luna.")),
                "misaka": (Mission(max=10, description="Deal killing blows with Railgun while under the effect of Electric Rage."),
                           Mission(max=10, description="Absorb killing blows while under the effect of Electric Rage."),
                           Mission(max=500, description="Deal or absorb damage with Iron Sand."),
                           Mission(max=15, description="Strike invulnerable enemies with Railgun."),
                           Mission(max=1000, description="Deal damage with Railgun.")),
                "kuroko": (Mission(max=30, description="Spend turns while invulnerable."),
                           Mission(max=25, description="Stun enemies with Needle Pin."),
                           Mission(max=20, description="Drain energy with Judgement Throw."),
                           Mission(max=15, description="Deal killing blows with Teleporting Strike."),
                           Mission(max=10, description="Use 3 different abilities in a row.")),
                "sogiita": (Mission(max=20, description="Consume at least 3 stacks of Guts with a single ability."),
                            Mission(max=15, description="Deal killing blows with Super Awesome Punch."),
                            Mission(max=1, description="Reach 10 stacks of Guts, then win the match."),
                            Mission(max=15, description="Deal killing blows with any member of your team against enemies affected by Overwhelming Suppression."),
                            Mission(max=400, description="Heal Gunha with Guts.")),
                "misaki": (Mission(max=15, description="Deal killing blows with enemies stunned by Mental Out."),
                           Mission(max=30, description="Deal killing blows with allies under the effect of Ally Mobilization."),
                           Mission(max=25, description="Spend 25 turns invulnerable with Loyal Guard."),
                           Mission(max=5, description="Use Exterior twice in a match, then win the match."),
                           Mission(max=5, description="Use Mental out on all 3 enemies in the same match, then win the match.")),
                "frenda": (Mission(max=60, description="Apply stacks of Doll Trap or Close-Combat Bombs."),
                           Mission(max=1, description="Kill all 3 enemies with a single Detonate."),
                           Mission(max=30, description="Deal killing blows with Detonate."),
                           Mission(max=1, description="Trigger Detonate with 2 stacks of Close Combat Bombs, and at least 7 stacks of Doll Trap."),
                           Mission(max=1, description="Deal the final killing blow of the match while only Frenda is alive, and below 25 health.")),
                "naruha": (Mission(max=15, description="Win matches without leaving Perfect Paper - Rampage Suit."),
                           Mission(max=10, description="Win 10 matches after Naruha has left Perfect Paper - Rampage Suit."),
                           Mission(max=750, description="Regenerate destructible defense with Rabbit Guard and Bunny Assault."),
                           Mission(max=25, description="Deal killing blows while in Perfect Paper - Rampage Suit."),
                           Mission(max=10, description="Deal killing blows with Enraged Blow.")),
                "tsunayoshi": (Mission(max=2000, description="Deal damage with X-Burner."),
                               Mission(max=10, description="Counter enemies with Zero Point Breakthrough."),
                               Mission(max=15, description="Stun enemies with Burning Axle."),
                               Mission(max=1, description="Kill all 3 enemies with a single X-Burner."),
                               Mission(max=1, description="Counter the same enemy with Zero Point Breakthrough twice in one game.")),
                "yamamoto": (Mission(max=20, description="Strike enemies with the enhanced version of Utsuhi Ame."),
                             Mission(max=20, description="Deal killing blows with Shinotsuku Ame."),
                             Mission(max=5, description="Reach 10 stacks of Rain Flames."),
                             Mission(max=1, description="Use Scontro di Rondine on an enemy affected by two stacks of Beccata di Rondine."),
                             Mission(max=25, description="Spend turns under the effect of Asari Ugetsu.")),
                "hibari": (Mission(max=1000, description="Deal damage with Bite You To Death."),
                           Mission(max=10, description="Deal killing blows to enemies stunned by Alaudi's Handcuffs."),
                           Mission(max=10, description="Deal killing blows to enemies under the effect of Porcospino Nuvola."),
                           Mission(max=30, description="Have enemies spend turns stunned."),
                           Mission(max=300, description="Deal damage with Porcospino Nuvola.")),
                "gokudera": (Mission(max=100, description="Progress the C.A.I. Stage."),
                             Mission(max=2000, description="Cause 2000 damage or healing with Sistema C.A.I."),
                             Mission(max=15, description="Deal killing blows with Sistema C.A.I. while Vongola Box Weapon - Vongola Bow is active."),
                             Mission(max=1, description="After activating Vongola Box Weapon, use Sistema C.A.I. three turns in a row."),
                             Mission(max=1, description="Fully cycle through Sistema C.A.I. three times in one match.")),
                "ryohei": (Mission(max=35, description="Deal killing blows with Maximum Cannon."),
                           Mission(max=1000, description="Heal allies with Kangaryu."),
                           Mission(max=100, description="Gain stacks of To The Extreme!"),
                           Mission(max=5, description="Use Maximum Cannon or Kangaryu with 5 or more stacks of To The Extreme!"),
                           Mission(max=1, description="Deal 100 or more damage with a single Maximum Cannon.")),
                "lambo": (Mission(max=15, description="Win matches without using Ten-Year Bazooka."),
                          Mission(max=10, description="Win matches while Lambo is a teenager."),
                          Mission(max=5, description="Win matches while Lambo is an adult."),
                          Mission(max=1000, description="Redirect damage with Conductivity."),
                          Mission(max=100, description="Spend turns with Summon Gyudon active.")),
                "chrome": (Mission(max=15, description="Win matches as Chrome."),
                           Mission(max=15, description="Win matches as Mukuro."),
                           Mission(max=20, description="Drain energy with Mental Immolation."),
                           Mission(max=30, description="Deal killing blows as Chrome or Mukuro."),
                           Mission(max=1, description="Deal all 3 killing blows in a match with Mukuro.")),
                "tatsumi": (Mission(max=1, description = "Strike an enemy with Neuntote three turns in a row."),
                            Mission(max=20, description="Use Killing Strike against enemies that are both stunned and below half health."),
                            Mission(max=500, description="Absorb damage with Incursio."),
                            Mission(max=1, description="Deal all 3 killing blows in a single match with Killing Strike."),
                            Mission(max=30, description="Deal killing blows with Tatsumi.")),
                "mine": (Mission(max=20, description="Deal killing blows against invulnerable enemies with Pumpkin Scouter active."),
                         Mission(max=20, description="Deal killing blows with Roman Artiller - Pumpkin while below 30 health."),
                         Mission(max=20, description="Deal killing blows with Cut-Down Shot while below 25 health."),
                         Mission(max=1, description="Kill all 3 enemies during the same turn."),
                         Mission(max=1, description="Deal 225 damage in a single match.")),
                "akame": (Mission(max=15, description="Deal killing blows under the effect of Little War Horn."),
                          Mission(max=30, description="Deal killing blows with Akame."),
                          Mission(max=1, description="Activate Little War Horn while Akame is the only living member of your team, then win the game."),
                          Mission(max=25, description="Mark enemies with Red-Eyed Killer."),
                          Mission(max=5, description="Deal all 3 killing blows in a match with Akame.")),
                "leone": (Mission(max=1000, description="Gain health through Leone's self-healing."),
                          Mission(max=40, description="Deal killing blows with Leone."),
                          Mission(max=25, description="Deal killing blows against enemies affected by Beast Instinct."),
                          Mission(max=20, description="Ignore 20 counters while affected by Beast Instinct."),
                          Mission(max=1, description="Take 200 damage with Leone in a single match.")),
                "raba": (Mission(max=25, description="Trigger the final effect of Cross-Tail Strike."),
                         Mission(max=25, description="Trigger the final effect of Wire Shield."),
                         Mission(max=25, description="Deal killing blows with Heartseeker Thrust."),
                         Mission(max=10, description="Win matches where Lubbock does not use Wire Shield."),
                         Mission(max=10, description="Win matches where Lubbock does not use Cross-Tail Strike.")),
                "sheele": (Mission(max=40, description="Deal killing blows with Sheele."),
                           Mission(max=25, description="Deal killing blows against enemies that are countering or ignoring effects."),
                           Mission(max=20, description="Interrupt continuous abilities with Savior Strike."),
                           Mission(max=25, description="Destroy destructible defense effects with Extase - Bisector of Creation."),
                           Mission(max=20, description="Deal killing blows on enemies stunned by Trump Card - Blinding Light.")),
                "seryu": (Mission(max=1000, description="Deal damage with Raging Koro."),
                          Mission(max=15, description="Deal killing blows with Insatiable Justice."),
                          Mission(max=10, description="Deal killing blows with Body Modification - Arm Gun against enemies affected by Berserker Howl."),
                          Mission(max=20, description="Deal killing blows against enemies damaged by both Body Modification - Arm Gun and Raging Koro."),
                          Mission(max=10, description="Deal killing blows with Body Modification - Self Destruct.")),
                "kurome": (Mission(max=15, description="Resurrect allies with Yatsufusa."),
                           Mission(max=20, description="Deal killing blows with Mass Reanimation after it has been boosted by Yatsufusa."),
                           Mission(max=10, description="Deal killing blows with allies resurrected by Yatsufusa."),
                           Mission(max=10, description="Receive abilities that would have killed Kurome while under the effect of Doping Rampage."),
                           Mission(max=20, description="Deal killing blows while under the effect of Doping Rampage.")),
                "esdeath": (Mission(max=25, description="Deal killing blows against enemies under the effect of Frozen Castle."),
                            Mission(max=40, description="Win marches with Esdeath."),
                            Mission(max=5, description = "Win matches in a row with Esdeath."),
                            Mission(max=15, description="Deal killing blows against enemies affected by Mahapadma."),
                            Mission(max=1, description="Activate Mahapadma while Esdeath is the only living member of your team, then win the match.")),
                "snowwhite": (Mission(max=30, description="Generate energy with Hear Distress."),
                              Mission(max=30, description="Counter enemies with Hear Distress."),
                              Mission(max=10, description="Revive allies with Lucky Rabbit's Foot."),
                              Mission(max=10, description="Win games without Snow White using Enhanced Strength."),
                              Mission(max=1, description="Deal the final killing blow of a match with a character who has been revived by Lucky Rabbit's Foot.")),
                "ruler":(Mission(max=20, description="Have In The Name Of Ruler! expire naturally."),
                         Mission(max=300, description="Deal or absorb damage with Minion - Minael and Yunael."),
                         Mission(max=15, description="Counter enemies with Minion - Tama."),
                         Mission(max=10, description="Activate In The Name Of Ruler! while under the effect of Minion - Minael and Yunael and Minion - Tama."),
                         Mission(max=20, description="Have allies deal the killing blow to enemies under the effect of In The Name of Ruler!")),
                "ripple": (Mission(max=30, description="Mark characters with Perfect Accuracy."),
                           Mission(max=20, description="Use Shuriken Throw against an enemy team that is entirely marked with Perfect Accuracy."),
                           Mission(max=20, description="Deal killing blows to enemies under the effect of Night of Countless Stars."),
                           Mission(max=10, description="Deal killing blows to invulnerable enemies."),
                           Mission(max=1, description="Deal all 3 killing blows in a single turn.")),
                "nemu": (Mission(max=300, description="Heal Nemurin with Nemurin Nap."),
                         Mission(max=20, description="Reduce the damage of a hostile, used ability with Nemurin Beam."),
                         Mission(max=20, description="Deal killing blows with allies under the effect of Dream Manipulation."),
                         Mission(max=1, description="After Nemurin has died, win the match with a character under the effect of Dream Manipulation."),
                         Mission(max=10, description="Win matches without Nemurin being dozing or awake for more than two turns.")),
                "cmary": (Mission(max=400, description="Deal damage with Hidden Mine."),
                          Mission(max=20, description="Deal killing blows with Grenade Toss against enemies affected by Hidden Mine."),
                          Mission(max=30, description="Deal killing blows with any Quickdraw ability."),
                          Mission(max=20, description="Spend turns invulnerable due to Quickdraw - Sniper."),
                          Mission(max=20, description="Have Hidden Mines expire without detonating.")),
                "cranberry": (Mission(max=25, description="Increase the cost of used enemy abilities with Illusory Disorientation."),
                              Mission(max=10, description="Deal killing blows with Merciless Finish."),
                              Mission(max=15, description="Ignore counter effects with Mental Radar."),
                              Mission(max=1000, description="Deal 1000 damage to invulnerable or ignoring enemies with Fortissimo."),
                              Mission(max=20, description="Have Illusory Disorientation expire naturally.")),
                "swimswim": (Mission(max=15, description="Deal killing blows on the turn following Dive."),
                             Mission(max=20, description="Deal killing blows while under the effect of Vitality Pill."),
                             Mission(max=10, description="Win matches with Swim Swim as your last living character."),
                             Mission(max=30, description="Spend turns under the effect of Dive."),
                             Mission(max=1, description="During a single match, affect Swim Swim with allied moves 5 times, then win the match.")),
                "pucelle": (Mission(max=20, description="Deal killing blows with Ideal Strike."),
                            Mission(max=25, description="Activate Grow."),
                            Mission(max=20, description="Deal killing blows with Knight's Sword."),
                            Mission(max=1, description="Deal 100 damage with a single Knight's Sword."),
                            Mission(max=1, description="Win a match with Ideal Strike while La Pucelle is your last living character.")),
                "chachamaru": (Mission(max=40, description="Mark targets with Target Lock."),
                               Mission(max=20, description="Spend turns under the effect of Active Combat Mode."),
                               Mission(max=20, description="Get killing blows with Orbital Satellite Cannon."),
                               Mission(max=1, description="Kill all 3 enemies with a single Orbital Satellite Cannon."),
                               Mission(max=300, description="Absorb damage with Active Combat Mode.")),
                "saitama": (Mission(max=50, description="Deal killing blows with One Punch."),
                            Mission(max=5, description="Keep Consecutive Normal Punches active on the same enemy for 7 consecutive turns."),
                            Mission(max=25, description="Ignore 25 enemy effects with Serious Series - Serious Punch."),
                            Mission(max=10, description="Win matches where Saitama only uses One Punch (at least once)."),
                            Mission(max=10, description="Get the killing blow on all 3 enemies in a single match.")),
                "tatsumaki": (Mission(max=40, description="Gain stacks of Gather Power."),
                              Mission(max=40, description="Receive hostile abilities with Arrest Assault."),
                              Mission(max=5, description="Deal killing blows with Return Assault."),
                              Mission(max=10, description="Use Return Assault with 3 stacks."),
                              Mission(max=25, description="Deal killing blows with Rubble Barrage.")),
                "mirai": (Mission(max=1000, description="Deal affliction damage with Mirai's abilities."),
                          Mission(max=25, description="Deal killing blows under the effect of Blood Suppression Removal."),
                          Mission(max=1, description="Deal 100 affliction damage to Mirai with Blood Suppression Removal, then win the match."),
                          Mission(max=20, description="Deal killing blows with the initial damage from Blood Sword Combat."),
                          Mission(max=15, description="Receive damaging abilities while under the effect of Blood Shield.")),
                "touka": (Mission(max=25, description="Counter abilities with Draw Stance."),
                          Mission(max=20, description="Use Raiou to increase the cooldown of a used enemy ability."),
                          Mission(max=20, description="Deal killing blows with Raikiri."),
                          Mission(max=25, description="Deal killing blows while under the effect of Nukiashi."),
                          Mission(max=5, description="Win matches without Draw Stance's counter being triggered.")),
                "killua": (Mission(max=30, description="Trigger the secondary effect of Lightning Palm."),
                           Mission(max=30, description="Trigger the secondary effect of Narukami."),
                           Mission(max=30, description="Trigger the secondary effect of Whirlwind Rush 30 times."),
                           Mission(max=30, description="Deal killing blows while under the effect of Godspeed."),
                           Mission(max=5, description="Win matches where Killua's secondary effects are always triggered.")),
                "byakuya": (Mission(max=0, description="N/A"),
                            Mission(max=0, description="N/A"),
                            Mission(max=0, description="N/A"),
                            Mission(max=0, description="N/A"),
                            Mission(max=0, description="N/A"))
            }